# Generated by Django 4.2.3 on 2023-07-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_login', '0002_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(default=0.0)),
                ('short_text', models.CharField(max_length=40)),
                ('product_description', models.TextField(verbose_name='product discription')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catagory', to='App_shop.catagory')),
                ('sellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sellar', to='App_login.sellar')),
            ],
        ),
    ]
