# Generated by Django 4.2.3 on 2023-07-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='purshed',
            new_name='purchased',
        ),
    ]
