# Generated by Django 4.2.3 on 2023-07-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0006_alter_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('delivard', 'delivard')], default=('processing', 'processing'), max_length=10),
        ),
    ]
