# Generated by Django 4.2.3 on 2023-07-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0009_remove_cart_status_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expaired', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_amount', models.IntegerField(default=2000)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_order.coupon'),
        ),
    ]
