# Generated by Django 4.2.3 on 2023-07-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0010_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(),
        ),
    ]
