# Generated by Django 4.2.3 on 2023-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0014_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('delivered', 'Delivered')], default='processing', max_length=10),
        ),
    ]
