# Generated by Django 4.2.3 on 2023-07-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0002_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=8.2, max_length=255),
            preserve_default=False,
        ),
    ]
